"""Built-in node registry and UI-facing specifications."""

from __future__ import annotations

from libreml_core.nodes import NodeDefinition, NodeRegistry
from libreml_core.schemas import PortDefinition, PortType, ResourceHints
from libreml_reporting import GenerateReportConfig, execute_generate_report

from .data import (
    AssignRolesConfig,
    CSVImportConfig,
    DatasetOverviewConfig,
    ExcelImportConfig,
    ParquetImportConfig,
    TabularPreprocessConfig,
    TrainTestSplitConfig,
    execute_assign_roles,
    execute_csv_import,
    execute_dataset_overview,
    execute_excel_import,
    execute_parquet_import,
    execute_tabular_preprocess,
    execute_train_test_split,
)
from .ml import (
    EvaluateModelConfig,
    ModelDefinitionConfig,
    TrainModelConfig,
    execute_evaluate_model,
    execute_model_definition,
    execute_train_model,
)


def _port(
    name: str, port_type: PortType, *, required: bool = True, description: str = ""
) -> PortDefinition:
    return PortDefinition(name=name, type=port_type, required=required, description=description)


def build_registry() -> NodeRegistry:
    registry = NodeRegistry()
    definitions = [
        NodeDefinition(
            type="csv_import",
            version="1.0.0",
            display_name="CSV Import",
            category="Data sources",
            description="Import a CSV or TSV from an explicitly allowed local path.",
            learning_explanation="Reads rows and columns from a local text data file without sending it anywhere.",
            research_explanation="Records a SHA-256 source fingerprint and enforces byte and row limits.",
            inputs=(),
            outputs=(_port("dataset", PortType.DATASET),),
            config_model=CSVImportConfig,
            execute=execute_csv_import,
            cacheable=False,
            resource_hints=ResourceHints(cpu="low", memory="medium"),
            documentation_ref="docs/nodes/csv-import.md",
        ),
        NodeDefinition(
            type="excel_import",
            version="1.0.0",
            display_name="Excel Import",
            category="Data sources",
            description="Import one sheet from a guarded local XLSX workbook.",
            learning_explanation="Reads values from one spreadsheet sheet; formulas are not executed.",
            research_explanation="Screens OOXML archives for unsafe paths and suspicious expansion before read-only parsing.",
            inputs=(),
            outputs=(_port("dataset", PortType.DATASET),),
            config_model=ExcelImportConfig,
            execute=execute_excel_import,
            cacheable=False,
            resource_hints=ResourceHints(cpu="low", memory="medium"),
        ),
        NodeDefinition(
            type="parquet_import",
            version="1.0.0",
            display_name="Parquet Import",
            category="Data sources",
            description="Import a local columnar Parquet dataset.",
            learning_explanation="Reads an efficient local data format often used for larger tables.",
            research_explanation="Checks metadata row and column bounds before materializing selected columns.",
            inputs=(),
            outputs=(_port("dataset", PortType.DATASET),),
            config_model=ParquetImportConfig,
            execute=execute_parquet_import,
            cacheable=False,
            resource_hints=ResourceHints(cpu="medium", memory="medium"),
        ),
        NodeDefinition(
            type="dataset_overview",
            version="1.0.0",
            display_name="Dataset Overview",
            category="Understand data",
            description="Profile shape, types, missingness, duplicates, distributions, and numeric summaries.",
            learning_explanation="Shows what is in the table and highlights data quality questions before modeling.",
            research_explanation="Computes unsampled descriptive statistics, confidence intervals for numeric means, and structured integrity warnings.",
            inputs=(_port("dataset", PortType.DATASET),),
            outputs=(_port("dataset", PortType.DATASET), _port("overview", PortType.OVERVIEW)),
            config_model=DatasetOverviewConfig,
            execute=execute_dataset_overview,
            resource_hints=ResourceHints(cpu="medium", memory="medium"),
        ),
        NodeDefinition(
            type="assign_roles",
            version="1.0.0",
            display_name="Assign Feature & Target Roles",
            category="Prepare data",
            description="Explicitly identify predictors, outcome, ignored fields, and task type.",
            learning_explanation="Features are the information used to predict; the target is what you want to predict.",
            research_explanation="Enforces disjoint variable roles and screens direct or name-suggested target leakage.",
            inputs=(_port("dataset", PortType.DATASET),),
            outputs=(_port("labeled_dataset", PortType.LABELED_DATASET),),
            config_model=AssignRolesConfig,
            execute=execute_assign_roles,
        ),
        NodeDefinition(
            type="train_test_split",
            version="1.0.0",
            display_name="Train/Test Split",
            category="Validate",
            description="Create reproducible training and final holdout partitions.",
            learning_explanation="The model learns from training rows and is checked on rows it did not train on.",
            research_explanation="Supports seeded random or classification-stratified splits and duplicate-boundary screening.",
            inputs=(_port("labeled_dataset", PortType.LABELED_DATASET),),
            outputs=(_port("split_dataset", PortType.SPLIT_DATASET),),
            config_model=TrainTestSplitConfig,
            execute=execute_train_test_split,
        ),
        NodeDefinition(
            type="tabular_preprocess",
            version="1.0.0",
            display_name="Tabular Preprocessing",
            category="Prepare data",
            description="Impute, scale, and one-hot encode using training data only.",
            learning_explanation="Fills missing inputs and converts categories into numbers the model can use.",
            research_explanation="Fits every learned preprocessing statistic exclusively on the training partition to prevent leakage.",
            inputs=(_port("split_dataset", PortType.SPLIT_DATASET),),
            outputs=(_port("prepared_dataset", PortType.PREPARED_DATASET),),
            config_model=TabularPreprocessConfig,
            execute=execute_tabular_preprocess,
            resource_hints=ResourceHints(cpu="medium", memory="high"),
        ),
        NodeDefinition(
            type="model_definition",
            version="1.0.0",
            display_name="Model Selection",
            category="Model",
            description="Select a supported regression or classification estimator and validated parameters.",
            learning_explanation="Chooses the mathematical pattern-finding method while keeping its settings visible.",
            research_explanation="Restricts parameters to reviewed estimator-specific allowlists with bounded values.",
            inputs=(),
            outputs=(_port("model_definition", PortType.MODEL_DEFINITION),),
            config_model=ModelDefinitionConfig,
            execute=execute_model_definition,
        ),
        NodeDefinition(
            type="train_model",
            version="1.0.0",
            display_name="Train Model",
            category="Model",
            description="Fit the selected estimator on the prepared training partition.",
            learning_explanation="Lets the selected model learn patterns from training examples.",
            research_explanation="Uses the recorded seed and retains the exact fitted preprocessing object with the estimator for inference.",
            inputs=(
                _port("prepared_dataset", PortType.PREPARED_DATASET),
                _port("model_definition", PortType.MODEL_DEFINITION),
            ),
            outputs=(_port("trained_model", PortType.TRAINED_MODEL),),
            config_model=TrainModelConfig,
            execute=execute_train_model,
            resource_hints=ResourceHints(cpu="high", memory="high", streams_progress=True),
        ),
        NodeDefinition(
            type="evaluate_model",
            version="1.0.0",
            display_name="Evaluate Model",
            category="Evaluate",
            description="Measure predictive performance on the untouched test partition.",
            learning_explanation="Checks how well the model works on examples it did not learn from and explains each score.",
            research_explanation="Reports task-appropriate holdout metrics, per-class diagnostics, baselines, and integrity warnings.",
            inputs=(_port("trained_model", PortType.TRAINED_MODEL),),
            outputs=(_port("metrics", PortType.METRICS),),
            config_model=EvaluateModelConfig,
            execute=execute_evaluate_model,
        ),
        NodeDefinition(
            type="generate_report",
            version="1.0.0",
            display_name="Research Report",
            category="Output",
            description="Create deterministic HTML, Markdown, and JSON reports locally.",
            learning_explanation="Turns methods, results, warnings, and limitations into a readable report.",
            research_explanation="Produces escaped, template-based multi-format output with provenance, package versions, and a software citation.",
            inputs=(_port("metrics", PortType.METRICS),),
            outputs=(_port("report", PortType.REPORT_ARTIFACT),),
            config_model=GenerateReportConfig,
            execute=execute_generate_report,
            cacheable=False,
        ),
    ]
    for definition in definitions:
        registry.register(definition)
    return registry
